name: Build macOS App (ARM64)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show project files (debug)
        run: |
          pwd
          ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pin to a stable toolchain
          pip install "pyinstaller==6.8" "pyinstaller-hooks-contrib>=2025.1"
          pip install PySide6 pandas openpyxl

      - name: Clean previous build dirs
        run: |
          rm -rf build dist GR24.spec || true

      # Build ARM64 .app with only the Qt modules we need (Widgets/Core/Gui)
      - name: Build .app with PyInstaller (ARM64 minimal Qt)
        run: |
          pyinstaller \
            --noconfirm --clean --windowed --name "GR24" \
            --collect-all PySide6 --collect-all shiboken6 \
            --exclude-module PySide6.Qt3D* \
            --exclude-module PySide6.QtBluetooth \
            --exclude-module PySide6.QtCharts \
            --exclude-module PySide6.QtDataVisualization \
            --exclude-module PySide6.QtDesigner \
            --exclude-module PySide6.QtHelp \
            --exclude-module PySide6.QtHttpServer \
            --exclude-module PySide6.QtLocation \
            --exclude-module PySide6.QtMultimedia* \
            --exclude-module PySide6.QtNetworkAuth \
            --exclude-module PySide6.QtNfc \
            --exclude-module PySide6.QtOpenGL* \
            --exclude-module PySide6.QtPdf* \
            --exclude-module PySide6.QtPositioning \
            --exclude-module PySide6.QtQml* \
            --exclude-module PySide6.QtQuick* \
            --exclude-module PySide6.QtRemoteObjects \
            --exclude-module PySide6.QtSensors \
            --exclude-module PySide6.QtSerial* \
            --exclude-module PySide6.QtStateMachine \
            --exclude-module PySide6.QtSvg* \
            --exclude-module PySide6.QtTest \
            --exclude-module PySide6.QtTextToSpeech \
            --exclude-module PySide6.QtUiTools \
            --exclude-module PySide6.QtWeb* \
            gr24_pricing_app.py

      - name: Ensure permissions & inspect binary
        run: |
          chmod +x "dist/GR24.app/Contents/MacOS/GR24" || true
          file "dist/GR24.app/Contents/MacOS/GR24"

      - name: Zip the app (preserves bundle metadata)
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent "GR24.app" "GR24_mac_arm64.zip"
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GR24-mac-arm64
          path: dist/GR24_mac_arm64.zip
          if-no-files-found: error
