name: Build macOS App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # setup-python installs the universal2 build

      - name: Show project files (debug)
        run: |
          pwd
          ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pin a recent, stable toolchain
          pip install "pyinstaller>=6.6" pyinstaller-hooks-contrib
          pip install PySide6 pandas openpyxl

      # Build a universal2 .app (runs on Intel & Apple Silicon)
      - name: Build .app with PyInstaller
        run: |
          pyinstaller --noconfirm --windowed --target-arch universal2 --name "GR24" gr24_pricing_app.py
          # Output: dist/GR24.app

      # Make sure the main binary is executable
      - name: Fix permissions & inspect
        run: |
          chmod +x "dist/GR24.app/Contents/MacOS/GR24" || true
          ls -la "dist/GR24.app/Contents/MacOS"
          file "dist/GR24.app/Contents/MacOS/GR24"   # shows architectures

      # Zip correctly on macOS (preserves bundle metadata)
      - name: Zip the app
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent "GR24.app" "GR24_mac.zip"
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GR24-mac
          path: dist/GR24_mac.zip
          if-no-files-found: error
