name: Build macOS App

on:
  workflow_dispatch:      # হাতে রান করতে পারবেন
  push:
    branches: [ main ]    # main এ push হলে অটো রান

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show project files (debug)
        run: |
          pwd
          ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 pandas openpyxl

      # .app বানাতে --onefile ব্যবহার করবেন না
      - name: Build .app with PyInstaller
        run: |
          pyinstaller --noconfirm --windowed --name "GR24" gr24_pricing_app.py
          # আউটপুট: dist/GR24.app

      # .app zip করলে পাঠানো সহজ হয়
      - name: Zip the app
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent "GR24.app" "GR24_mac.zip"
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GR24-mac
          path: dist/GR24_mac.zip
          if-no-files-found: error
