name: Build macOS App (ARM64)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest   # GitHub runners are ARM64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show project files (debug)
        run: |
          pwd
          ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pyinstaller>=6.6" pyinstaller-hooks-contrib
          pip install PySide6 pandas openpyxl

      - name: Build .app with PyInstaller (ARM64)
        run: |
          # No --target-arch; build native (arm64) to avoid universal2 issues
          pyinstaller --noconfirm --windowed --collect-all PySide6 --name "GR24" gr24_pricing_app.py
          # Output: dist/GR24.app

      - name: Fix permissions & inspect
        run: |
          chmod +x "dist/GR24.app/Contents/MacOS/GR24" || true
          file "dist/GR24.app/Contents/MacOS/GR24"

      - name: Zip the app
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent "GR24.app" "GR24_mac_arm64.zip"
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GR24-mac-arm64
          path: dist/GR24_mac_arm64.zip
          if-no-files-found: error
