name: Build Win & Mac

on:
  workflow_dispatch:        # ম্যানুয়ালি রান
  push:
    branches: [ main ]      # main-এ push হলেই চলবে

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 pandas openpyxl

      - name: Build
        run: |
          pyinstaller --noconfirm --onefile --windowed gr24_pricing_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/*
