name: Build Win & Mac

on:
  workflow_dispatch:   # চাইলে ম্যানুয়ালি রান করবেন
  push:
    branches: [ main ] # main এ push হলে অটো রান হবে

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show project files (debug)
        run: |
          echo "Current path:" 
          pwd
          echo "Files here:"
          ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 pandas openpyxl

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed gr24_pricing_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*
          if-no-files-found: error
